[package]
name = "jnigen_shared"
version = "0.1.0"
authors = ["Maximilian Goisser <goisser94@gmail.com>"]

[dependencies]
cargo_metadata = "0.6"
serde = "1.0.80"
serde_json = "1.0.32"
serde_derive = "1.0.80"
file-lock = "1.1"
