/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class some_pkg_HelloWorld */

#ifndef _Included_some_pkg_HelloWorld
#define _Included_some_pkg_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     some_pkg_HelloWorld
 * Method:    hello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_some_pkg_HelloWorld_hello
  (JNIEnv *, jobject, jstring);

/*
 * Class:     some_pkg_HelloWorld
 * Method:    plusOne
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_some_pkg_HelloWorld_plusOne
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
